schema = 1

[distribution]
name = "loclass"
version = "0.3.0"
python = ">=3.14"

[installation]
data_directory = "~/.local/share/loclass"
binary_directory = "~/.local/bin"

[[components]]
id = "loclass-ldl"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-ldl.git"
tag = "v0.2.0"
commit = "8f488dbd896b68d82524bcab979e32987d7cd150"
dependencies = []

[[components]]
id = "loclass-base"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-base.git"
tag = "v0.4.0"
commit = "681a41ad1f87d5c206d55fe7321b0117dbb1d0bd"
dependencies = ["loclass-ldl"]

[[components]]
id = "loclass-mermaid"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-mermaid.git"
tag = "v0.1.0"
commit = "7b2d705c44ddd6eeca3ba441f3bcab14d5e23473"
dependencies = ["loclass-base"]

[[components]]
id = "loclass-tlp"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-tlp.git"
tag = "v0.1.0"
commit = "8d777fe9dd4ae4ed9145b48d12bd1543fbb62ca7"
dependencies = ["loclass-base"]

[[components]]
id = "loclass-review"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-review.git"
tag = "v0.2.0"
commit = "b9add04ad5cd4ef115b890e4daed9ad4e8b93f9b"
dependencies = ["loclass-base"]

[[components]]
id = "loclass-starter"
kind = "starter"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-starter.git"
tag = "v0.2.0"
commit = "fd155ab18015409e73a0dea1feaece71ca2e02e8"
dependencies = []

[[components]]
id = "loclass-cockpit"
kind = "lua"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-cockpit.git"
tag = "v0.1.1"
commit = "e9544ef340ccefcfa51427a5d2237ba9526d88a5"
dependencies = ["loclass-base", "loclass-starter"]
