schema = 1

[distribution]
name = "loclass"
version = "0.4.2"
python = ">=3.14"

[installation]
data_directory = "~/.local/share/loclass"
binary_directory = "~/.local/bin"

[[components]]
id = "loclass-ldl"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-ldl.git"
tag = "v0.2.0"
commit = "8f488dbd896b68d82524bcab979e32987d7cd150"
dependencies = []

[[components]]
id = "loclass-base"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-base.git"
tag = "v0.4.1"
commit = "3488949a45751108ea75d7aad43ff2eebff68be3"
dependencies = ["loclass-ldl"]

[[components]]
id = "loclass-mermaid"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-mermaid.git"
tag = "v0.1.0"
commit = "7b2d705c44ddd6eeca3ba441f3bcab14d5e23473"
dependencies = ["loclass-base"]

[[components]]
id = "loclass-tlp"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-tlp.git"
tag = "v0.1.0"
commit = "8d777fe9dd4ae4ed9145b48d12bd1543fbb62ca7"
dependencies = ["loclass-base"]

[[components]]
id = "loclass-review"
kind = "python"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-review.git"
tag = "v0.2.0"
commit = "b9add04ad5cd4ef115b890e4daed9ad4e8b93f9b"
dependencies = ["loclass-base"]

[[components]]
id = "loclass-starter"
kind = "starter"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-starter.git"
tag = "v0.3.1"
commit = "f37af56870739d72320fba5c42d0b301ce577b68"
dependencies = []

[[components]]
id = "loclass-cockpit"
kind = "lua"
repository = "ssh://git@git.home.arpa:2222/loclass/loclass-cockpit.git"
tag = "v0.2.0"
commit = "b00357d7a3a5f888090eeb71ecc39766bb6c946a"
dependencies = ["loclass-base", "loclass-starter"]
